//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 02:10:40 AM CST 
//


package org.example.student;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HOME" type="{http://www.example.org/Student}Address"/>
 *         &lt;element name="COMMUNICATION" type="{http://www.example.org/Student}Address"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "home",
    "communication"
})
public class AddressType {

    @XmlElement(name = "HOME", required = true)
    protected Address home;
    @XmlElement(name = "COMMUNICATION", required = true)
    protected Address communication;

    /**
     * Gets the value of the home property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getHOME() {
        return home;
    }

    /**
     * Sets the value of the home property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setHOME(Address value) {
        this.home = value;
    }

    /**
     * Gets the value of the communication property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getCOMMUNICATION() {
        return communication;
    }

    /**
     * Sets the value of the communication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setCOMMUNICATION(Address value) {
        this.communication = value;
    }

}
